from matplotlib import pyplot as plt
a=input('Aの値')
A=int(a)
b=input('Bの値')
B=int(b)
c=input('Cの値')
C=int(c)
d=input('Dの値')
D=int(d)
e=input('Eの値')
E=int(e)
name = input("タイトルを入力")
color = input("カラー")
print("作成完了")
data = [A, B, C, D, E]
plt.title(name)
plt.plot(data,color=color,marker="o")
plt.show()
